services:
  app:
    build: ./docker
    ports: 
      - "80:80"
    volumes: 
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secretpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "81:80"
    environment:
      PMA_HOST: db
      PMA_USER: app_user
      PMA_PASSWORD: secretpass

volumes:
  db-data:
