name: AWSサービス作成

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/aws_resource_create.yml'
      - 'aws_resource_check.sh'
# on:
#   workflow_run:
#     workflows: [DockerfileのBuildとECRリポジトリ作成＆Push]
#     types:
#       - completed

jobs:
  aws_resource_create:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - name: github clone
        uses: actions/checkout@v4

      - name: aws_access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraformのセットアップ
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        working-directory: terraform/resource
        run: |
          terraform init

      - name: AWS既存resourceチェック
        working-directory: terraform/resource
        run: |
          sh aws_resource_check.sh

      - name: terraform plan
        working-directory: terraform/resource
        run: terraform plan -var="aws_region=${{secrets.AWS_REGION}}"

      - name: terraform apply
        working-directory: terraform/resource
        run: terraform apply -auto-approve -var="aws_region=${{secrets.AWS_REGION}}"