on:
  push:
    paths:
      - 'terraform/repository/**'
      - 'docker/**'
      - '.github/workflows/build.yml'

jobs:
  aws_access:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: aws_access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: terraform/repository
        run: terraform init

      - name: Terraform apply (ECRリポジトリ作成のみ)
        working-directory: terraform/repository
        run: |
          terraform apply -auto-approve \
            -target="aws_ecr_repository.sample_repository"

      - name: ecrログイン
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: sample_repository
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./docker
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG