name: aws_access_check

on: [push]

jobs:
  aws_access:
    runs-on: ubuntu-latest
    steps:
      - name: github clone
        uses: actions/checkout@v4

      - name: aws_access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraformのセットアップ
        uses: hashicorp/setup-terraform@v3

      - run: |
          if aws ec2 describe-vpcs --filter "Name=dougbako" > /dev/null 2>&1; then
          echo "ありました";
          else
          echo "ありませんでした";
          fi

      # - run: terraform init
      # - run: terraform plan
      # - run: terraform apply -auto-approve
