name: aws_access_check

on: [push]

jobs:
  aws_access:
    runs-on: ubuntu-latest
    steps:
      - name: github clone
        uses: actions/checkout@v4

      - name: aws_access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: |
          VPC_ID="vpc-09cfd7c0d10b311f5"
          if aws ec2 describe-vpcs --vpc-ids $VPC_ID > /dev/null 2>&1; then
            echo "VPC $VPC_ID ありました下記詳細です."
            aws ec2 describe-vpcs --vpc-ids $VPC_ID
          else
            echo "VPC $VPC_ID ありません."
          fi
