name: aws_access_check

on: [push]

jobs:
  aws_access:
    runs-on: ubuntu-latest
    steps:
      - name: github clone
        uses: actions/checkout@v4

      - name: aws_access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraformのセットアップ
        uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - name: AWS既存resourceチェック
        run: |
          sh aws_resource_check.sh

      - run: terraform plan
      - run: terraform apply -auto-approve -var="aws_region=${{secrets.AWS_REGION}}"
